---
- hosts: control_plane
  become: yes
  vars:
    - packages: ["git", "nmap"]
    - user: "admin"
  tasks:
    - name: initialize the cluster
      shell:
        cmd: kubeadm init >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: "{{user}}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{user}}/.kube/config
        remote_src: yes
        owner: "{{user}}"

    - name: Install Helm in Control plane
      shell:
        cmd:  curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh

    - name: Install git inorder to pull Nginx Ingress Controller
      yum_repository:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: install Pod network
      shell:
        cmd: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml