- hosts: control_plane
  become: yes
  vars:
      - user: "admin"
  tasks:
  - name: Install nginx web server
    yum:
      name: nginx
      state: installed
      update_cache: yes
    notify:
      - start nginx