- hosts: control_plane
  become: yes
  vars:
      - user: "admin"
      - pg_kong_host: "127.0.0.1"
      - pg_kong_password: :"password"
      - pg_kong_user: "postgres"
      - pg_kong_port: "5432"
      - pg_kong_database: "kong"
  tasks:
   - name: Install yum utils
     yum:
       name: yum-utils
       state: latest

   - name: Install device-mapper-persistent-data
     yum:
       name: device-mapper-persistent-data
       state: latest

   - name: Install lvm2
     yum:
       name: lvm2
       state: latest

   - name: Add Kong repo
     get_url:
       url: https://download.konghq.com/gateway-3.x-centos-7/config.repo
       dest: /etc/yum.repos.d/kong.repo
     become: yes

   - name: Install Kong
     package:
       name: kong
       state: present
       nobest: true
     become: yes

   - name: Check Kong if installed succesfully
     shell: kong roar
     register: kong_status

   - debug: msg="{{ kong_status.stdout }}"

   - name: Added Kong configuration
     copy:
      dest: "/etc/kong/kong.conf"
      content: |
          database = postgres
          pg_host = {{pg_kong_host}}
          pg_port = {{pg_kong_port}}
          pg_timeout = 5000
          pg_user = {{pg_kong_user}}
          pg_password = {{pg_kong_password}}
          pg_database = {{pg_kong_database}}

   - name: Set ulimit to 4096 temporarily
     shell: sudo ulimit -n 4096

   - name: Kong Migration
     shell: kong kong migrations bootstrap -c /etc/kong/kong.conf
     register: kong_status_bootstrap

   - debug: msg="{{ kong_status_bootstrap.stdout }}"

   - name: Kong Migration
     shell: kong migrations up -c /etc/kong/kong.conf
     register: kong_status_migration

   - debug: msg="{{ kong_status_migration.stdout }}"

   - name: Start Kong
     shell: kong start -c /etc/kong/kong.conf

   - name: Print out Success message
     debug:
       msg:
        - "Kong Has start we all ready to roll :)"



