- hosts: control_plane
  become: yes
  vars:
      - user: "admin"
  tasks:
  - name: Install nginx web server
    yum:
      name: nginx
      state: installed
      update_cache: yes
    notify:
      - start nginx

  - name: Start nginx web server
    shell:
      name: nginx
      state: installed
      update_cache: yes
    notify:
      - start nginx

  - name: Start nginx and enabled
    systemd:
      name: nginx
      state: started
      enabled: yes
