- hosts: control_plane
  become: yes
  vars:
      - user: "admin"
  tasks:
  - name: Install nginx web server
    yum:
      name: nginx
      state: installed
      update_cache: yes
    notify:
      - start nginx

  - name: Start nginx and enabled
    shell: sudo systemctl enable nginx && sudo systemctl start nginx

  - name: Install Epel-Release
    dnf:
      name: epel-release
      state: present


  - name: Install Certbot
    dnf:
      name: certbot
      state: present

  - name: Install Nginx module for Certbot
    dnf:
      name: python3-certbot-nginx
      state: present

  - name: Install Mod_SSL
    dnf:
      name: mod_ssl
      state: present