- hosts: control_plane
  become: yes
  vars:
      - user: "admin"
      - pg-kong-host: "127.0.0.1"
      - pg-pg-password: :"password"
  tasks:
   - name: Install yum utils
     yum:
       name: yum-utils
       state: latest

   - name: Install device-mapper-persistent-data
     yum:
       name: device-mapper-persistent-data
       state: latest

   - name: Install lvm2
     yum:
       name: lvm2
       state: latest

   - name: Add Kong repo
     get_url:
       url: https://download.konghq.com/gateway-3.x-centos-7/config.repo
       dest: /etc/yum.repos.d/kong.repo
     become: yes

   - name: Install Kong
     package:
       name: kong
       state: present
       nobest: true
     become: yes

    - name: Check Kong if installed succesfully
      shell: kong roar
      register: kong_status
      debug:
       var: kong_status
       verbosity: 2

   - name: Added Kong configuration
     copy:
      dest: "/etc/kong/kong.conf"
      content: |
          database = postgres
          pg_host = "{{pg-kong-host}}"
          pg_port = 5432
          pg_timeout = 5000
          pg_user = kong
          pg_password = "{{pg-pg-password}}"
          pg_database = kong




