---
- hosts: all
  become: yes
  tasks:
   - name: create Docker config directory
     file: path=/etc/docker state=directory

   - name: changing Docker to systemd driver
     copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }

   - name: install Docker
     yum:
       name: docker.io
       state: present
       update_cache: true

   - name: Enable EPEL Repository
     dnf:
       name: epel-release
       state: latest
     become: true
     when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

   - name: Enable EPEL Repository
     yum:
       name: epel-release
       state: latest
     become: true
     when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'

  #  - name: Start Docker Service
  #    shell:
  #       cmd: sudo systemctl start docker

   - name: write repo information in kube repo file
     blockinfile:
       path: "/etc/yum.repos.d/kubernetes.repo"
       block: |
             [kubernetes]
             name=Kubernetes
             enabled=1
             gpgcheck=1
             repo_gpgcheck=1
             gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

   - name: install kubelet
     yum:
       name: kubelet=1.22.4-00
       state: present
       update_cache: true

   - name: install kubeadm
     yum:
       name: kubeadm=1.22.4-00
       state: present

- hosts: control_plane
  become: yes
  tasks:
   - name: install kubectl
     yum:
       name: kubectl=1.22.4-00
       state: present
       force: yes