---
- hosts: control_plane
  become: yes
  vars:
      - user: "admin"
  tasks:
    - name: initialize the cluster
      shell:
        cmd: kubeadm init

    - name: create .kube directory
      become: yes
      become_user: "{{user}}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{user}}/.kube/config
        remote_src: yes
        owner: "{{user}}"

    # - name: install Pod network
    #   become: yes
    #   become_user: ubuntu
    #   shell:
    #     cmd:  kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
    #   args:
    #     chdir: $HOME
    #     creates: pod_network_setup.txt

    - name: Install Helm in Control plane
      shell:
        cmd: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh

    - name: Install git inorder to pull Nginx Ingress Controller
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Adding Nginx Controller Repository using Helm
      shell:
        cmd:  helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update Helm Repository
      shell:
        cmd: helm repo update

    - name: Installing  nginx-ingress controller
      shell:
        cmd: helm install nginx-ingress ingress-nginx/ingress-nginx
